server:
  port: 8085

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: cab.aggregator.notification@gmail.com
    password: ftkhczeqidieyauo
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

kafka:
  bootstrap-servers: kafka:9092
  ride-status-topic-name: ride-status-topic
  group-id: ${spring.application.name}