server:
  port: 8085

spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: cab.aggregator.notification@gmail.com
    password: ftkhczeqidieyauo
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrap-servers: localhost:9092
  ride-status-topic-name: ride-status-topic
  group-id: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"