server:
  port: 8082

spring:
  application:
    name: driver-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: cab.aggregator.notification@gmail.com
    password: ftkhczeqidieyauo
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true