global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'eureka-server'
    relabel_configs:
      - source_labels: [ __meta_eureka_app_instance_metadata_prometheus_path ]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
    eureka_sd_configs:
      - server: http://host.docker.internal:8761/eureka

  - job_name: 'kafka-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]