server:
  port: 8084

spring:
  application:
    name: rating-service

  datasource:
    url: jdbc:postgresql://localhost:5432/rating_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: db/changelog/changelog-master.xml

  cloud:
    openfeign:
      client:
        config:
          ride-service:
            url: http://localhost:8083

springdoc:
  override-with-generic-response: false
  api-docs:
    path: /rating-service/v3/api-docs

kafka:
  passenger-rating-topic-name: passenger-rating-topic
  driver-rating-topic-name: driver-rating-topic
  bootstrap-servers: localhost:9092

logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    com.zaxxer.hikari.pool.HikariPool: DEBUG
    com.modsen.ratingservice.client: DEBUG
