server:
  port: 8082

spring:
  application:
    name: driver-service

  datasource:
    url: jdbc:postgresql://localhost:5432/driver_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: db/changelog/changelog-master.xml

  cloud:
    function:
      definition: acceptRideOrder;updateDriverRating
    stream:
      bindings:
        acceptRideOrder-in-0:
          destination: ${kafka.create-ride-topic}
          group: ${spring.application.name}
        acceptRideOrder-out-0:
          destination: ${kafka.accept-ride-topic}
        updateDriverRating-in-0:
          destination: ${kafka.update-driver-rating-topic}
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
            - ${kafka.bootstrap-servers}
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer


springdoc:
  override-with-generic-response: false

kafka:
  create-ride-topic-name: create-ride-topic
  accept-ride-topic-name: accept-ride-topic
  update-driver-rating-topic-name: update-driver-rating-topic
  bootstrap-servers: localhost:9092
