server:
  port: 8083

spring:
  application:
    name: ride-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ride_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: db/changelog/changelog-master.xml

  cloud:
    openfeign:
      client:
        config:
          passenger:
            url: http://localhost:8081/api/v1/passengers

springdoc:
  override-with-generic-response: false

driver-client:
  driver-service-uri: http://localhost:8082

kafka:
  create-ride-topic-name: create-ride-topic
  accept-ride-topic-name: accept-ride-topic
  ride-status-topic-name: ride-status-topic
  driver-status-topic-name: driver-status-topic
  bootstrap-servers: localhost:9092
  group-id: ${spring.application.name}
